"""Public typed domain and stage contracts for entity resolution."""

from hsds_entity_resolution.types.contracts import (
    ApplyMitigationResult,
    CleanEntitiesResult,
    ClusterPairsResult,
    GenerateCandidatesResult,
    IncrementalRunResult,
    MaterializeReviewQueueResult,
    PreparePersistenceArtifactsResult,
    ScoreCandidatesResult,
)
from hsds_entity_resolution.types.domain import (
    EntityId,
    EntityType,
    ModelVersion,
    PairKey,
    PolicyVersion,
    ScopeId,
    TeamId,
)
from hsds_entity_resolution.types.frames import (
    CANDIDATE_PAIR_SCHEMA,
    CLEAN_ENTITY_SCHEMA,
    CLUSTER_PAIRS_SCHEMA,
    CLUSTERS_SCHEMA,
    CONTRIBUTING_REASONS_SCHEMA,
    ENTITY_INDEX_SCHEMA,
    FINALIZED_PAIRS_SCHEMA,
    MITIGATION_EVENTS_SCHEMA,
    PAIR_ID_REMAP_SCHEMA,
    PAIR_REASONS_SCHEMA,
    PAIR_STATE_INDEX_SCHEMA,
    REMOVED_PAIR_IDS_SCHEMA,
    REVIEW_QUEUE_SCHEMA,
    SCORED_PAIRS_SCHEMA,
)

__all__ = [
    "ApplyMitigationResult",
    "CANDIDATE_PAIR_SCHEMA",
    "CLEAN_ENTITY_SCHEMA",
    "CLUSTER_PAIRS_SCHEMA",
    "CLUSTERS_SCHEMA",
    "CONTRIBUTING_REASONS_SCHEMA",
    "CleanEntitiesResult",
    "ClusterPairsResult",
    "ENTITY_INDEX_SCHEMA",
    "EntityId",
    "EntityType",
    "FINALIZED_PAIRS_SCHEMA",
    "GenerateCandidatesResult",
    "IncrementalRunResult",
    "MITIGATION_EVENTS_SCHEMA",
    "MaterializeReviewQueueResult",
    "ModelVersion",
    "PAIR_ID_REMAP_SCHEMA",
    "PAIR_REASONS_SCHEMA",
    "PAIR_STATE_INDEX_SCHEMA",
    "PreparePersistenceArtifactsResult",
    "PairKey",
    "PolicyVersion",
    "REMOVED_PAIR_IDS_SCHEMA",
    "REVIEW_QUEUE_SCHEMA",
    "SCORED_PAIRS_SCHEMA",
    "ScopeId",
    "ScoreCandidatesResult",
    "TeamId",
]
